### ISSUE TITLE
cookie.parse did not to be executed

### ISSUE THREAD

**Issue by blackbing** [thereactivestack/react-cookie#48]
hi I upgrade to the latest version[1.0.1] but there's something problem. I didn't see what's difference between the older version, but I saw `IS_NODE` always true both in browser or node environment. It might be the problem why cookie.parse wasn't executed.

https://github.com/thereactivestack/react-cookie/blob/master/src/cookie.js#L13

**Comment by dmeenhuis** [comment]
Same problem here with ``cookie.load``. I think the first check in the referenced line is wrong; for Node environments I would assume ``document`` is undefined, since ``document`` is a browser thing.

**Comment by blackbing** [comment]
@dmeenhuis yes. that's the part what i confused.

**Comment by eXon** [comment]
The 1.0 version has no major API change, but it's a rewrite with `import` and since it is widely used in production, I though it was time to bump to 1.0.

I'll fix this real quick.

**Comment by swaggy** [comment]
This is broken in 0.4.9 too.

**Comment by eXon** [comment]
Should be fixed in 1.0.2

**Comment by blackbing** [comment]
@eXon I've test it in `1.0.2`, but the this statement is not going to work.
```
typeof module !== 'undefined' && module.exports;
```
because `module` is defined by webpack environment.

**Comment by echaouchna** [comment]
@eXon I've test it in 1.0.2 but it's not working in webpack environment.

BTW I've found an npm package called [is-node](https://github.com/MatthewNPM/is-node) that has a different implementation of is-node :

```
!!(typeof process !== 'undefined' && process.versions && process.versions.node)
```

I've tried it and it seems to be working

**Comment by eXon** [comment]
@echaouchna should be fixed in 1.0.3 sorry about that. thank for the tip

**Comment by echaouchna** [comment]
Now it's working

Thank you

**Comment by sylvainpina** [comment]
Hello @eXon, i still have this issue :(
i use webpack@1.14.
on a my server express it's ok, but on a browser IS_NODE is true
see this console.log() (a log for the lib is-node it's present too): 
```javascript
/* node */
react-cookie:(typeof document === "undefined"),  true
react-cookie:(process && process.env && process.env.NODE_ENV === "test"),  false
react-cookie:IS_NODE,  true
is-node: (!!(typeof process !== "undefined" && process.versions && process.versions.node)),  true
```
```javascript
/* browser */
react-cookie:(typeof document === "undefined"),  false
react-cookie:(process && process.env && process.env.NODE_ENV === "test"),  true
react-cookie:IS_NODE,  true
is-node: (!!(typeof process !== "undefined" && process.versions && process.versions.node)),  false
```

please consider the solution of the lib `is-node`, thx
